### ISSUE TITLE
Anonymous aggregate in math library

### ISSUE THREAD

**Issue by agayev169** [AliKhudiyev/LayZ-Renderer-Engine#1]
I am getting ```error: member ‘lyz::math::vec3 lyz::math::vec4::<unnamed union>::<unnamed struct>::u_vec’ with constructor not allowed in anonymous aggregate``` and a bunch of other similar errors for destructors and copy constructors of the classes from math library.

**Comment by AliKhudiyev** [comment]
It's very unfortunate that GCC does such kind of "shitlik" and does not allow unnamed structures inside an unnamed union. **BUT** I have managed to fix this issue by *rEmOvInG tHeM*!
